import type { NextPage } from "next";
import Head from "next/head";
import { PageTemplate } from "@/components/page-template";
import Styles from "./internals.module.css";
import { Character } from "@/components/character";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>OnFood</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTemplate>
        <div className={Styles.container}>
          <h1>Encontre opções em Delivery próximas á você.</h1>


          <h2>
            Descubra seu novo Delivery favorito. Milhares de opções a um clique.
          </h2>
          <Character />
        </div>

      </PageTemplate>
    </>
  );
};

export default Home;
